### ISSUE TITLE
There is some mistakes in "UNetBlock" function

### ISSUE THREAD

**Issue by zhongtao93** [Mutoy-choi/Tryondiffusion#1]
https://github.com/Mutoy-choi/Tryondiffusion/blob/9508623ac10163850b053858a11390c3088a49dc/parallelUNet128.py#L75
Thanks for sharing code! When I run the code, I find some mistakes:
1. when in_channels != out_channels, will go errors. This can be fixed by modify line 67-68
2. TypeError: forward() got an unexpected keyword argument 'garment_pose_embedding'

**Comment by Mutoy-choi** [comment]
Thank you for comment. i'm trying to debug whole code now
