### ISSUE TITLE
concatenate the segmented garment Ic and the noisy image zt 

### ISSUE THREAD

**Issue by liguiming77** [Mutoy-choi/Tryondiffusion#3]
In paper,  'concatenate the segmented garment Ic and the noisy image zt along the  channel dimension' ,in this repo,concatenate two pictures along the H dimension,Do I have an exact understanding?

**Comment by Mutoy-choi** [comment]
Yes, the train code concatenate two pictures along the H dimension

**Comment by Mutoy-choi** [comment]
> In paper, 'concatenate the segmented garment Ic and the noisy image zt along the channel dimension' ,in this repo,concatenate two pictures along the H dimension,Do I have an exact understanding?

Yes, the train code concatenate two pictures along the H(height) dimension
