### ISSUE TITLE
diffusion process

### ISSUE THREAD

**Issue by zhaoxinf** [Mutoy-choi/Tryondiffusion#4]
hi! Thanks for your great coding work. However, I cannot find the diffusion process in your code, it seems there is no diffusion forward-reverse process right?

**Comment by 24thTinyGiant** [comment]
I also want to ask the same question as asked above

**Comment by Mutoy-choi** [comment]
> hi! Thanks for your great coding work. However, I cannot find the diffusion process in your code, it seems there is no diffusion forward-reverse process right?

https://github.com/Mutoy-choi/Tryondiffusion/blob/main/models/EfficientUNet.py this is diffusion process
this model use efficientnet for encoder and then goes with upblock.

https://github.com/Mutoy-choi/Tryondiffusion/blob/main/dataloader/EfficientUnetDataloader.py
This is dataloader 

https://github.com/Mutoy-choi/Tryondiffusion/blob/main/train/train_EfficientUNet.py
This is train code
