### ISSUE TITLE
Hello! How is it going? Need help? 

### ISSUE THREAD

**Issue by dexforint** [Mutoy-choi/Tryondiffusion#5]
Hello! How is it going (are weights available)? Need help? if Yes - please contact via telegram: dl_hello

**Comment by Mutoy-choi** [comment]
> Hello! How is it going (are weights available)? Need help? if Yes - please contact via telegram: dl_hello


Hi! I'm now working on other project (korean-ai-competition) so i don't have much time to spend in this project. 
What I'm doing now is adjusting the structure of the pre-processing process and model little by little to train with AI-Hub's data. Unlike VITON dataset, AI-Hub's data shows many kinds of clothes (hat, top and bottom, etc.), front and back poses, so I'm making adjustments to this.
